services:
  app:
    image: node:14  
    working_dir: /app
    volumes:
    - ./src:/app/src  # Monte le répertoire 'src' de votre hôte dans '/app/src' à l'intérieur du conteneur
    - ./Backend:/app/Backend  # Monte le répertoire 'Backend' de votre hôte dans '/app/Backend'
    - ./components:/app/components  # Monte le répertoire 'components' de votre hôte dans '/app/components'
    - ./screens:/app/screens  # Monte le répertoire 'screens' de votre hôte dans '/app/screens'
    - ./socket:/app/socket  # Monte le répertoire 'socket' de votre hôte dans '/app/socket'
    - ./App.js:/app/App.js  # Monte le fichier 'App.js' de votre hôte dans '/app/App.js' à l'intérieur du conteneur

    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD= 
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    command: node App.js  # Commande pour démarrer  l'application

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest  # Image SQL Server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"  # Mappez le port de la base de données SQL Server sur le port local
