name : Arosaje CI

on :
  push:
    branches: [nali900m-test]
  pull_request:
    branches: [nali900m-test]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installation des dépendances
    # --legacy-peer-deps pour éviter les problèmes de dépendances
      run: npm ci --legacy-peer-deps
    - name: execution des tests
      run: npm run test --if-present
    
